@URL = https://railwaycallfit-production.up.railway.app


############################################################
# USUARIO
############################################################

### GET - Obtener usuarios
GET {{URL}}/usuario

###

### POST - Crear usuario
POST {{URL}}/usuario
Content-Type: application/json

{
    "nombre": "Christian",
    "apellido": "Ramos",
    "fecha_nacimiento": "2008-02-6",
    "email": "christian.ramos@gmail.com",
    "contrasenia": "123456",
    "contexto_aceptado": true
}


############################################################
# CONDICION
############################################################

### GET - Obtener condiciones
GET {{URL}}/condicion

###

### POST - Crear condicion
POST {{URL}}/condicion
Content-Type: application/json

{
    "condicion": "Control general"
}


############################################################
# RECETAS
############################################################

### GET - Obtener recetas
GET {{URL}}/recetas

###

### POST - Crear receta
POST {{URL}}/recetas
Content-Type: application/json

{
    "titulo": "Pollo con arroz",
    "descripcion": "Pechuga de pollo con arroz integral",
    "imagen": "pollo-arroz.jpg",
    "porcion": "1 porción",
    "calorias": 450,
    "proteinas": 35,
    "carbohidratos": 45,
    "grasas": 12,
    "sodio": 300,
    "id_condicion": 1,
    "ingredientes": "Pechuga de pollo, arroz integral y zanahoria",
    "preparacion": "Cocinar el arroz. Cocinar el pollo y servir con las verduras."
}


############################################################
# REGISTRO GLUCOSA
############################################################

### GET - Obtener registros
GET {{URL}}/registro_glucosa

###

### POST - Crear registro
POST {{URL}}/registro_glucosa
Content-Type: application/json

{
    "glucosa": 190,
    "fecha": "2026-10-05 14:25:00",
    "Usuario_id": 1,
    "nota": "Después del almuerzo",
    "comentarios": "Me siento bien"
}


############################################################
# PLAN SEMANAL
############################################################

### GET - Obtener plan semanal
GET {{URL}}/plan_semanal

###

### POST - Crear plan semanal
POST {{URL}}/plan_semanal
Content-Type: application/json

{
    "Usuario_id": 1,
    "id_receta": 1,
    "dia": "Lunes",
    "comida": "Almuerzo"
}